sudo: required
dist: trusty
group: edge

language: java
# jdk: oraclejdk10

notifications:
  email:
    on_success: never
    on_failure: always

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - build
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: build
      install:
      - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
      - . ./install-jdk.sh -F 10 -L GPL
      script:
      - ./gradlew :json-iterator:check
      - ./gradlew :json-iterator:jacocoTestReport
      - bash <(curl -s https://codecov.io/bash)
    - stage: publish
      install:
      - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
      - . ./install-jdk.sh -F 10 -L GPL
      script:
      - ./gradlew :json-iterator:bintrayUpload
