language: java

env: JDK=12

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source install-jdk.sh -F 12

notifications:
  email:
    on_success: never
    on_failure: always

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
    if: tag IS blank
  - name: publish
    if: tag IS present

jobs:
  include:
  - stage: build
    name: "Build, Test and Code Coverage"
    script:
    - ./gradlew --no-daemon check
  - stage: publish
    name: "Publish to Bintray"
    script:
    - ./gradlew --no-daemon check
    - ./gradlew --no-daemon :json-iterator:bintrayUpload
