name: CI

on:
  create:
    tags:
      - '*'
  push:
    branches:
      - master
  pull_request:
  schedule: 
    - cron:  '0 0 * * 1,4'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        
    - name: Gradle Check
      run: ./gradlew check --stacktrace

#    - name: Github Publish
#      env:
#        GITHUB_USER: ${{ secrets.GITHUB_USER }}
#        GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
#      run: ./gradlew :json-iterator:publishMavenJavaPublicationToGithubPackageRegistryRepository
#      if: success() && github.event_name == 'create'
        
    - name: Publish
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
      run: ./gradlew :json-iterator:bintrayUpload
      if: success() && github.event_name == 'create'
