name: Gradle Nightly Check

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 1,4'

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties

      - uses: actions/setup-java@v1
        with:
          java-version: 14-ea
      - run: java --version
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: nightly
          arguments: check  -PtargetJava=14 --warning-mode=all --stacktrace

