name: Gradle Check

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * 1,4'

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - run: java --version

      - name: Gradle Check
        run: ./gradlew check --stacktrace

      - uses: gradle/wrapper-validation-action@v1