name: Gradle Check

on:
  push:
    branches:
      - master
  pull_request:
  schedule: 
    - cron:  '0 0 * * 1,4'

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - uses: actions/setup-java@v1
      with:
        java-version: 13
    - run: java --version
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: check --stacktrace