name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 12
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --stacktrace

      - name: Bintray Publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :json-iterator:bintrayUpload
        if: success() && github.event_name == 'create'

#    - name: Github Publish
#      env:
#        GITHUB_USER: ${{ secrets.GITHUB_USER }}
#        GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
#      run: ./gradlew :json-iterator:publishMavenJavaPublicationToGithubPackageRegistryRepository
#      if: success() && github.event_name == 'create'
